### ISSUE TITLE
LZX Compression

### ISSUE THREAD

**Issue by luke0x90** [libyal/libfwnt#13]
Is LZX Compression going to be added? Thanks!

**Comment by joachimmetz** [comment]
Isn't this already there? https://github.com/libyal/libfwnt/blob/main/include/libfwnt.h.in#L412

**Comment by luke0x90** [comment]
Is that not LZX Decompression only?

**Comment by joachimmetz** [comment]
yes this project focuses on decompression only

**Comment by luke0x90** [comment]
Ah I saw compression implementations and thought it may have been planned (eg https://github.com/libyal/libfwnt/blob/main/libfwnt/libfwnt_lzxpress.h#L51)

**Comment by joachimmetz** [comment]
just an idea for now, not actually planned, and definitely not short term

**Comment by joachimmetz** [comment]
Sure, just be aware of the maintainability of the resulting code:

* needs to be C89 compatible and cross-platform (to support building for some exotic backwards compatible platforms)
* stick with the current code style
* have decent test coverage
