### ISSUE TITLE
libfwnt_locale_identifier_language_tag_get_identifier missing from exported functions in DLL?

### ISSUE THREAD

**Issue by brechtsanders** [libyal/libfwnt#7]
When building on Windows with MinGW I had issues caused by libfwnt_locale_identifier_language_tag_get_identifier() not being exported.
The command below fixes this problem:
```
patch -ulbf libfwnt/libfwnt_locale_identifier.h << EOF
@@ -26,2 +26,3 @@
 #include <types.h>
+#include <libfwnt_extern.h>

@@ -48,6 +49,6 @@

-const char *libfwnt_locale_identifier_language_tag_get_identifier(
+LIBFWNT_EXTERN const char *libfwnt_locale_identifier_language_tag_get_identifier(
              uint16_t lcid_language_tag );

-const char *libfwnt_locale_identifier_language_tag_get_description(
+LIBFWNT_EXTERN const char *libfwnt_locale_identifier_language_tag_get_description(
              uint16_t lcid_language_tag );
EOF
```

**Comment by joachimmetz** [comment]
libfwnt_locale_identifier_language_tag_get_identifier is not an API function at this time (also see https://github.com/libyal/libfwnt/blob/master/include/libfwnt.h.in). In what context did you got the missing function message?

**Comment by joachimmetz** [comment]
No response from reporter closing issue.
